#!/usr/bin/env bash
# Scaffold three isolated StructuredDocs stacks on one VPS.
#
# Creates:
#   <base-dir>/test
#   <base-dir>/training
#   <base-dir>/production
#
# In each environment directory, ensures:
#   - .env (seeded from envs/<env>.env.example when missing)
#   - .enable_blueprints
#   - docker-compose.single.yml
#   - data/images and instance directories
#
# Optional behavior:
#   - clone repo into each environment directory if missing
#
# Usage:
#   ./scripts/scaffold_single_vps_three_stacks.sh \
#     --base-dir /opt/structureddocs \
#     --repo-url https://github.com/JoeRyanMBA/StructuredDocs.git \
#     --branch main

set -euo pipefail

BASE_DIR="/opt/structureddocs"
REPO_URL=""
BRANCH="main"

usage() {
  cat <<'USAGE'
Usage: scaffold_single_vps_three_stacks.sh [options]

Options:
  --base-dir <path>   Base directory for environment stacks (default: /opt/structureddocs)
  --repo-url <url>    Git URL to clone if environment folder has no .git
  --branch <name>     Git branch used when cloning (default: main)
  -h, --help          Show this help

Notes:
  - If --repo-url is omitted, the script still scaffolds directories and files.
  - Existing files are preserved unless explicitly regenerated by this script.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-dir)
      BASE_DIR="$2"
      shift 2
      ;;
    --repo-url)
      REPO_URL="$2"
      shift 2
      ;;
    --branch)
      BRANCH="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

declare -A PORT_BY_ENV=(
  [test]=18080
  [training]=28080
  [production]=38080
)

create_blueprints_file() {
  local target="$1/.enable_blueprints"
  if [[ -f "$target" ]]; then
    return
  fi

  cat > "$target" <<'BLUEPRINTS'
auth
collections
topics
publications
images
search
admin
imports
reviews
variables
snippets
notifications
milestones
feedback
tags
links
export
BLUEPRINTS
}

create_compose_file() {
  local env_name="$1"
  local env_dir="$2"
  local host_port="$3"
  local target="$env_dir/docker-compose.single.yml"

  cat > "$target" <<EOF
services:
  app:
    build: .
    environment:
      - PORT=8080
      - DATABASE_URL=\${DATABASE_URL}
      - DISABLE_SQLITE_FALLBACK=1
      - ENABLE_BLUEPRINTS_FILE=.enable_blueprints
      - STORAGE_BACKEND=local
      - IMAGE_STORAGE_ROOT=/app/data/images
      - FRONTEND_URL=\${FRONTEND_URL}
      - SECRET_KEY=\${SECRET_KEY}
      - JWT_SECRET_KEY=\${JWT_SECRET_KEY}
      - EMAIL_PROVIDER=\${EMAIL_PROVIDER:-smtp}
      - SMTP_SERVER=\${SMTP_SERVER:-}
      - SMTP_PORT=\${SMTP_PORT:-587}
      - SMTP_USERNAME=\${SMTP_USERNAME:-}
      - SMTP_PASSWORD=\${SMTP_PASSWORD:-}
      - SMTP_USE_SSL=\${SMTP_USE_SSL:-false}
      - DEFAULT_FROM_EMAIL=\${DEFAULT_FROM_EMAIL:-no-reply@yourdomain.com}
      - FROM_EMAIL=\${FROM_EMAIL:-}
      - FROM_NAME=\${FROM_NAME:-StructuredDocs}
      - ADMIN_API_KEY=\${ADMIN_API_KEY}
      - RUN_DB_MIGRATIONS=\${RUN_DB_MIGRATIONS:-1}
    ports:
      - "${host_port}:8080"
    restart: unless-stopped
    volumes:
      - ./.enable_blueprints:/app/.enable_blueprints:ro
      - ./instance:/app/instance
      - ./data/images:/app/data/images
      - ./data/images:/app/backend/static/images
    command: ["./start.sh"]
EOF

  echo "Wrote $target (${env_name}, host port ${host_port})"
}

seed_env_file() {
  local env_name="$1"
  local env_dir="$2"
  local template="$REPO_ROOT/envs/${env_name}.env.example"
  local target="$env_dir/.env"

  if [[ -f "$target" ]]; then
    echo "Keeping existing $target"
    return
  fi

  if [[ -f "$template" ]]; then
    cp "$template" "$target"
    echo "Seeded $target from $template"
  else
    cat > "$target" <<EOF
APP_ENV=${env_name}
PORT=8080
FLASK_ENV=production
SECRET_KEY=CHANGE_ME_${env_name}_SECRET
JWT_SECRET_KEY=CHANGE_ME_${env_name}_JWT_SECRET
DATABASE_URL=postgresql://CHANGE_ME@DB_HOST:5432/structureddocs_${env_name}
DISABLE_SQLITE_FALLBACK=1
FRONTEND_URL=https://${env_name}.yourdomain.com
ADMIN_API_KEY=CHANGE_ME_${env_name}_ADMIN_KEY
RUN_DB_MIGRATIONS=1
EOF
    echo "Created fallback $target"
  fi
}

clone_repo_if_needed() {
  local env_dir="$1"
  if [[ -z "$REPO_URL" ]]; then
    return
  fi

  if [[ -d "$env_dir/.git" ]]; then
    echo "Repo already present at $env_dir"
    return
  fi

  if [[ -n "$(ls -A "$env_dir" 2>/dev/null || true)" ]]; then
    echo "Skipping clone in non-empty directory: $env_dir"
    return
  fi

  git clone --branch "$BRANCH" "$REPO_URL" "$env_dir"
  echo "Cloned $REPO_URL ($BRANCH) into $env_dir"
}

mkdir -p "$BASE_DIR"

for env_name in test training production; do
  env_dir="$BASE_DIR/$env_name"
  host_port="${PORT_BY_ENV[$env_name]}"

  mkdir -p "$env_dir"
  clone_repo_if_needed "$env_dir"

  mkdir -p "$env_dir/data/images" "$env_dir/instance"
  chmod 777 "$env_dir/data/images" "$env_dir/instance"

  seed_env_file "$env_name" "$env_dir"
  create_blueprints_file "$env_dir"
  create_compose_file "$env_name" "$env_dir" "$host_port"
done

cat <<EOF

Scaffold complete.

Environment folders:
  $BASE_DIR/test      (port 18080)
  $BASE_DIR/training  (port 28080)
  $BASE_DIR/production (port 38080)

Next steps per environment:
  1) Edit .env secrets and DATABASE_URL
  2) Start stack:
     docker compose -f docker-compose.single.yml --env-file .env up -d --build
  3) Verify health:
     curl -sS http://127.0.0.1:<port>/api/health

Use Caddy template at:
  $REPO_ROOT/Caddyfile.single-vps.template
EOF

