"""Add User model and review fields to Topic

Revision ID: 16afd4356602
Revises: 485930d2d2e9
Create Date: 2025-07-27 11:03:05.690707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16afd4356602'
down_revision = '485930d2d2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('author', 'reviewer', 'admin', name='user_role'), server_default='author', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_reviewer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('review_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewer_comments', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('draft', 'published', 'archived', 'pending_review', name='topic_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
        batch_op.create_foreign_key('fk_topics_assigned_reviewer', 'users', ['assigned_reviewer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_topics_assigned_reviewer', type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'published', 'archived', 'pending_review', name='topic_status'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
        batch_op.drop_column('reviewer_comments')
        batch_op.drop_column('review_notes')
        batch_op.drop_column('review_due_date')
        batch_op.drop_column('assigned_reviewer_id')

    op.drop_table('users')
    # ### end Alembic commands ###
