"""Add import review_step enum

Revision ID: 3607b9acbc96
Revises: 9f935b8ff4f1
Create Date: 2025-07-24 09:29:26.888320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3607b9acbc96'
down_revision = '9f935b8ff4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_step', sa.Enum('pending', 'sme_approved', 'final_approved', name='import_review_step'), server_default='pending', nullable=False))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('draft', 'published', 'archived', name='topic_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'published', 'archived', name='topic_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))

    with op.batch_alter_table('import_documents', schema=None) as batch_op:
        batch_op.drop_column('review_step')

    # ### end Alembic commands ###
