"""Refactor import models

Revision ID: 44fd532081fa
Revises: c9d51b293237
Create Date: 2025-07-23 15:52:18.343443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fd532081fa'
down_revision = 'c9d51b293237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('heading_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('committed_topic', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committed_topic'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['import_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_documents', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('frontmatter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frontmatter', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))

    op.drop_table('import_items')
    # ### end Alembic commands ###
