"""Add collection_topic_tree table

Revision ID: 485930d2d2e9
Revises: 1497248490d9
Create Date: 2025-07-25 16:03:57.200463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485930d2d2e9'
down_revision = '1497248490d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_topic_tree',
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('parent_topic_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE')
    )
    op.drop_table('collection_topics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_topics',
    sa.Column('collection_id', sa.INTEGER(), nullable=True),
    sa.Column('topic_id', sa.INTEGER(), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE')
    )
    op.drop_table('collection_topic_tree')
    # ### end Alembic commands ###
