"""Add ImportImage model for tracking imported images

Revision ID: 70457456e747
Revises: 20250730_add_title_type_to_notification
Create Date: 2025-08-01 23:15:57.188339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70457456e747'
down_revision = '20250730_add_title_type_to_notification'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('public_url', sa.String(length=512), nullable=False),
    sa.Column('backend_path', sa.String(length=512), nullable=False),
    sa.Column('frontend_path', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['import_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_images')
    # ### end Alembic commands ###
