"""Add draft status to Topic

Revision ID: 9f935b8ff4f1
Revises: 44fd532081fa
Create Date: 2025-07-23 20:42:33.000124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f935b8ff4f1'
down_revision = '44fd532081fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(
    sa.Column('status', sa.String(length=20), nullable=False, server_default='draft')
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
