"""add follow_up_sent_at to reviews

Revision ID: ceac11c5e665
Revises: 87eeb4c4233f
Create Date: 2025-08-17 20:55:22.225501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceac11c5e665'
down_revision = '87eeb4c4233f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('follow_up_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'follow_up_sent_at')
    # ### end Alembic commands ###
