"""add_review_sequences_tables

Revision ID: e43f15c67e8b
Revises: 07f342e56ae5
Create Date: 2025-08-17 22:42:39.316821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43f15c67e8b'
down_revision = '07f342e56ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'paused', 'cancelled', name='sequence_status'), server_default='active', nullable=False),
    sa.Column('current_position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('auto_advance_on_approve', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('pause_on_changes', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['stakeholders.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_sequence_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=200), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'completed', 'skipped', name='step_status'), server_default='pending', nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['stakeholders.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['review_sequences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sequence_position', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reviews_sequence_id', 'review_sequences', ['sequence_id'], ['id'])

    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('author', 'reviewer', 'subject_matter_expert', 'stakeholder', 'admin', name='stakeholder_role'),
               nullable=False,
               existing_server_default=sa.text('("stakeholder")'))
        batch_op.alter_column('can_review',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('draft', 'pending_review', 'revisions_requested', 'approved', 'published', 'rejected', 'archived', name='topic_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'pending_review', 'revisions_requested', 'approved', 'published', 'rejected', 'archived', name='topic_status'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))

    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.alter_column('can_review',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('role',
               existing_type=sa.Enum('author', 'reviewer', 'subject_matter_expert', 'stakeholder', 'admin', name='stakeholder_role'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text('("stakeholder")'))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sequence_position')
        batch_op.drop_column('sequence_id')

    op.drop_table('review_sequence_steps')
    op.drop_table('review_sequences')
    # ### end Alembic commands ###
