"""add_description_to_collections

Revision ID: f2f2c9b34aae
Revises: 20250806_add_form_number
Create Date: 2025-08-08 21:19:11.450977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f2c9b34aae'
down_revision = '20250806_add_form_number'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'description')
    # ### end Alembic commands ###
